### ISSUE TITLE
Mobile usability issues

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2277]
kai, os shell
- [x] keyboard does not come up during pin entry
- [x] cannot dismiss pin entry when joining a device

**Comment by thure** [comment]
> keyboard does not come up during pin entry
As it turns out, this is unexpectedly nontrivial: https://gist.github.com/cathyxz/73739c1bdea7d7011abb236541dc9aaa

**Comment by thure** [comment]
Having done some more research and tried a few things, I'm at a loss.

The best workaround for now is for the user (I know :/) to tap outside the input, then tap back in. We're encountering weirdness where iOS Safari is doing everything _but_ opening the keyboard when calling `.focus()` outside of a click handler, and annoyingly Apple sees this as by-design.

iOS _requires_ the user to tap something in order to open the keyboard. It's not something that can be faked, though [we could listen for any tapping and focus the input then](https://stackoverflow.com/a/35368807/392113).

Perhaps the best solution would be to only autofocus on non-iOS browsers, though UA sniffing is always a bit of a smell…

**Comment by thure** [comment]
I think this is reasonably resolved by #2284, please reopen if there are further issues.
