### ISSUE TITLE
Friendlier errors when signaling server misconfigured

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2677]
- [x] if we use an http signaling url the client needs to throw friendly errors
- [x] socket errors from client when using `wss` with localhost signaling
- [ ] creating an invitation with failing signaling server should not be allowed (invite button disabled when signaling isnt there)

from #2444

**Comment by wittjosiah** [comment]
@richburdon @dmaretskyi 

> creating an invitation with failing signaling server should not be allowed (invite button disabled when signaling isnt there)

In order to accomplish this I think we need to expose the status of the signal manager over the network service. The signal manager is currently exposed by the network manager but there's a note to remove that. Given that, I'm wondering if the network manager status should be revamped to be more comprehensive and include the signal status (and potentially peer statuses later).

This is not devtools-specific functionality as apps will want to show the connection status to different peers/services.

**Comment by dmaretskyi** [comment]
SignalManager is a separate component - it is passed into the network managers constructor. You could add relavent getters to the signal manger directly, and pass it into the service that needs it

**Comment by mykola-vrmchk** [comment]
> SignalManager is a separate component - it is passed into the network managers constructor. You could add relavent getters to the signal manger directly, and pass it into the service that needs it

There is relevant getters in SignalManager, and even method to get signal status in the Devtools service, so it is a matter of moving it to the Network service (cc @wittjosiah)

**Comment by wittjosiah** [comment]
My concern is that the only way to access the signal manger in the service currently this https://github.com/dxos/dxos/blob/main/packages/core/mesh/network-manager/src/network-manager.ts#L109-L112. @dmaretskyi Are you suggesting passing the signal manager directly to the service context so that it could be used by any services that require it?

I have no problem with hooking it up however, but want to make sure we're on the same page because I don't want to refactor those in the opposite direction of what you were planning.
