### ISSUE TITLE
E2E tests for prod and dev environemts

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#2878]
- Setup tests that periodically check our KUBEs/apps/and SDK deployed to prod & dev environments
- Tests are setup as github action jobs running periodically (every hour).
- Test code is stored in `protocols` repo: `/e2e/...`.
- Should separatelly test prod & dev environments (use github actions matrix syntax)
- Each test is a separate github job
- Tests may be organized as mocha test suits.

### Signaling

- Script checks that kubes deliver messages (against `kube.dxos.org` or `kube.dev.dxos.org`)
- Script checks that joning and querying swarms works

### SDK

- **Install latest code from NPM, dont use local sources**
- Using client SDK, create identity, space
- Perform invitaiton between two peers and replicate data

### Apps

- Curl our app endpoints
- can we have a generic "does this app load?" test with playwright?
- Run existing playwright tests against deployed apps: `{halo,kai,composer}.[dev.]dxos.org`

## Reporting results

- Results will be visible in github actions UI
- We can sepratelly setup a custom dashboard to show latest run results
- Github graphql api can be used with an access token to query data about runs
- Consider using https://www.atlassian.com/software/statuspage as the dashboard, we'd need to build a simple api endpoint that calls github and returns status to atlassian

## Organizing code

- Could we build those tests in a way where they don't require hooking into our monorepo build process?
- Seprate packages under `e2e` directory, that install our latest SDK from NPM (and other deps like mocha & playwright)

**Comment by wittjosiah** [comment]
- re: Signalling
  - rather than setting up our own custom solution for this it seems like it would be worthwhile if we could take advantage of existing tooling instead
  - something like https://k6.io/ seems like a great candidate for this (it has http by default but also support protocol extensions https://k6.io/docs/extensions/ and browser-based tests https://k6.io/docs/javascript-api/k6-browser/)
  - I realize using this would mean either developing an http gateway for signal or a k6 dxrpc extension, but both of those sound more useful in the long term
- re: SDK
  - yes I think this makes sense, we need this kind of test setup for the templates anyways so that will likely cover the core sdk functionality
  - this is a test that feels like it should be run after each release more than every single day, but wouldn't hurt to run periodically
- re: Apps
  - running our existing playwright tests periodically against deployed environments and reporting the results somewhere sounds like a good idea to me, we're already writing and maintaining them for other purposes so I don't think it will be a significant lift to run them on different targets (just need to ensure we run the version of the tests which match the release version)
- this might be a separate stream, but I'd also propose re-introducing some unit test checks for breaking changes (both to the storage and the protocol). My suggestion would be to get these in place asap so we can start to learn about how often we're breaking things, even if we aren't holding ourselves to them yet (i.e. if it's snapshot-based, just reset the snapshot whenever but maybe log/alert whenever that happens so that we're aware of it).
- re: reporting results
  - Datadog has a k6 cloud integration to pull in reports https://docs.datadoghq.com/integrations/k6/
  - Datadog supports uploading of junit xml test reports https://docs.datadoghq.com/continuous_integration/tests/junit_upload/
  - Statuspage supports displaying a status based on a value in Datadog https://www.atlassian.com/software/statuspage/integrations
- re: Organizing code
  -  pnpm seems to be fine with us including external versions of our packages in our workspace and syncpack can be told to ignore the testing package by adding a new version group like:
```
  - packages:
      - '@dxos/external'
    dependencies:
      - '@dxos/*'
 ```

**Comment by dmaretskyi** [comment]
tests should always install latest packages from npm (no lockfiles)

**Comment by dmaretskyi** [comment]
(https://github.com/dxos/protocols/blob/fac059b85578e07f3781c47a76b207428e371118/packages/core/mesh/messaging/src/messenger.test.ts)
