### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3139]
### Old

- Just components anywhere in app tree (developer's layout)
- Controlled (app owns state)

```tsx
export const AppContainer = () => {
  const [open, setOpen] = useState(false);
  return (
    <PanelSidebarProvider
      open={open}
      sidebar={<Sidebar onToggle={() => setOpen(false)} />}
    >
      <SpacePanel onToggle={() => setOpen(false)} />
    </PanelSidebarProvider>
  );
};
```

### New

- Uncontrolled container
- Sidebar tightly coupled to Main (e.g., Main has defaultSidebarOpen property)
- Requires special hooks (useMainContext) that aren't intuitively related sidebar semantics
  -  E.g., I'm currently developing an app and trying to figure out what string to pass into the hook.
  - Feels arbitrary to bind a bane to a Rect component.
- Hooks access must be downstream (e.g., can't have key bindings higher up stack)
- Unclear how children of MainRoot work (additional components? swap order of sidebar?)
- Potential for "main" to grow into a larger framework

```tsx
export const AppContainer = () => {
  return (
    <MainRoot>
      <MainOverlay />
      <SidebarRoot className='!block-start-appbar'>
        <Sidebar />
      </SidebarRoot>
      <Main className='pbs-header bs-full overflow-hidden'>
        <SpacePanel />
      </Main>
    </MainRoot>
  );
};
```

### Feedback

- Make sidebar wrapper controlled
- Uncouple form Main
- slight preference for Content/Container over Main/Root (as a developer, I own "main")

**Comment by thure** [comment]
> Old: Just components anywhere in app tree (developer's layout)

That is not how the old component worked. The new component is not different in this regard, it just uses different names and doesn’t use slots.

> Old: Controlled (app owns state)

This is still possible with the new component:
```tsx
export const AppContainer = () => {
  const [open, setOpen] = useState(false);
  return (
    <MainRoot
      sidebarOpen={open}
      onSidebarOpenChange={setOpen}
    >
      <Sidebar onToggle={() => setOpen(false)} /> // where `Sidebar` is an app component that will render aurora’s Sidebar
      <SpacePanel onToggle={() => setOpen(false)} /> // where `SpacePanel` is an app component that will render aurora’s Main
    </MainRoot>
  );
};
```

> Uncontrolled container

If I understand this to mean the state is uncontrolled, that is actually the case for the old component, the new one uses controllable states like any other stateful Radix component or vanilla Input component.

If this is about using slots to render children, the parent never had that degree of control – it is not possible to control what children get rendered whether you use a prop that accepts ReactNode or use Radix-style contexts, e.g. `<Root slot={<><Thing/><Thing/></>} />` and `<Root><Slot><Thing/><Thing/></Slot></Root>` are functionally equivalent, but the ecosystem shows preference for the latter.

> Sidebar tightly coupled to Main (e.g., ~~Main~~ `MainRoot` has defaultSidebarOpen property)

This is intentional. We may need to coordinate styles applied to the main content area, rightly rendered as `<main>`, with _unique_, page-level secondary surfaces that affect its layout, e.g. a sidebar, topbar, table of contents, and footer.

`MainRoot` is just a provider and renders no element. `Main` also doesn’t have to render a `<main>`:

```tsx
<Main asChild>
  <div>{children}</div>
</Main>
```

The name `Main` refers only to the element `<main>`, it isn't meant to imply that this is meant to sit at the very top of your app.

> Requires special hooks (useMainContext) that aren't intuitively related sidebar semantics …

I can accept the argument that this could be made more ergonomic with e.g. `useSidebarToggle`. I can work on that.

> Hooks access must be downstream

This situation has improved, in fact you ran into this issue with `PanelSidebarProvider` last week. You can now render `MainRoot` very high up in the app, then use sidebar state in the same component you render `<Sidebar/>` which was not possible before.

> Unclear how children of MainRoot work (additional components? swap order of sidebar?)

I'm not sure it's any more clear than it was before, e.g.:

```tsx
// old
<PanelSidebarProvider slots={ sidebar: { children: <SidebarContent/> } }>
  {children}
</PanelSidebarProvider>
// new
<MainRoot>
  <Sidebar><SidebarContent/></Sidebar>
  <Main>{children}</Main>
<MainRoot/>
```

`PanelSidebarProvider` does do the sidebar rendering for you, but it provides context and renders the sidebar all at once, which has the hooks problem I mentioned above. It also means the developer is expected to know which props should go where in `slots`, whereas in the new pattern the components have completely flat props which should be much more ergonomic.

**Comment by richburdon** [comment]
Summary:

- re properties vs. children. i do think a sidebar property (not a slot) is clearer than requiring two children
- per previous chats -- how can i control the width of the sidbar (and other properties -- e.g., open animation)
- re state -- sorry i missed that -- so it can just be controlled and managed by the app's own state?
- re Radix's Root suffix -- OK i like the consistency then

> We may need to coordinate styles applied to the main content area, rightly rendered as <main>, with unique, page-level secondary surfaces that affect its layout, e.g. a sidebar, topbar, table of contents, and footer.

I don't understand this point, so can you critique the specific example i gave above.

```tsx
    <PanelSidebarProvider
      open={open}
      sidebar={<Sidebar onToggle={() => setOpen(false)} />}
    >
      <SpacePanel onToggle={() => setOpen(false)} />
    </PanelSidebarProvider>
```

- simple controlled component, which is able to style the "bounding" div that controls both the sidebar panel and `<main>` container
- no main/framework level semantics
- doesn't preclude other elements being added by the user (e.g., topbar/footer)
- less code; and i would argue less ambiguity
- opens the possibility of options like putting the sidebar on the left

I'm not arguing strongly for this, but my feedback is the new approach feels much heavier -- i.e., i'm now in a framework rather than assembling my own components. i don't see what we're gaining -- but again -- i think i'm likely not understanding the specific.

**Comment by thure** [comment]
> i do think a sidebar property (not a slot) is clearer than requiring two children

This view is at odds with Radix’s principles… it will be difficult to support `ReactNode` props in an ecosystem that is increasingly avoiding that pattern in favor of context-aware children. If this is a major concern for you, let’s discuss.

> how can i control the width of the sidebar

By setting the `className` prop on the `Sidebar` component:

```tsx
const { sidebarOpen } = useMainContext('MyComponent');
return <>
  <Sidebar className={['md:is-8', !sidebarOpen && 'md:-inline-start-8']}><MySidebarContent></Sidebar>
  <Main className={[sidebarOpen && 'pis-8']}><MyMainContent/></Main>
</>
```

Note that it’s a bit complicated now that it has different widths at different breakpoints, per the earlier request for sidebar to be full width on the smallest breakpoints. Its position when closed just needs to match its width at that breakpoint.

> it can just be controlled and managed by the app's own state?

Yes, that’s the idea at least.

> which is able to style the "bounding" div

Aurora offers no such bounding div, the app has always needed to provide that

> simple controlled component

In this design you’d need to drill props, e.g. `setSidebarOpen`, down to any components that should be able to change sidebar state, since there is no context provider. It also relies on a `ReactNode` prop which constrains configurability in ways I've highlighted before:
- If your `SidebarRoot` were to ever offer a context, you could not use the context in the same component that renders `SidebarRoot`
- The ecosystem, as far as I can tell, is deprecating `ReactNode` props, and Radix avoids the pattern in principle

> no main/framework level semantics

I would argue this is unavoidable, and feels akin to asking what is the sound of a single hand clapping? The Sidebar can’t exist in a vacuum – in large viewports, it changes the layout of its accompanying main content. It was already this way; rendering a component called `Sidebar` was already invoking main/framework-level semantics.

> doesn't preclude other elements being added by the user

The new pattern does not preclude this either:
```tsx
<MainRoot>
  <Sidebar {...}/>
  <Topbar {...}/>
  <Main {...}/>
  <Footer {...}/>
</MainRoot>
```
I actually intended it to be used this way.

> less code; and i would argue less ambiguity

Maybe that’s true. I think the solution space for those problems are probably out-of-scope for Aurora’s core, but not for a more abstract UI package like Mosaic.

> opens the possibility of options like putting the sidebar on the left

This was part of the design for both the old and the new sidebar. I want to enable this feature with a `side` prop:

```tsx
// this would use logical properties, so instead of `left` or `right, either `start` and `end` or `inline-start` and `inline-end`
<MainRoot sidebarSide='end'>{...}</MainRoot>
```

I think you could even have two sidebars:

```tsx
<MainRoot sidebarSide='both'>
  <Sidebar side='start'>{...}</Sidebar>
  <Sidebar side='end'>{...}</Sidebar>
</MainRoot>
```

Though that would mean the context would need a bit more nuance so both can be controlled properly.

> what does it mean to "render Aurora's sidebar" 

What I mean by “render {package}’s {component}” is
```tsx
import {Component} from 'package'
const ___ = () => {
  // …
  return <…><Component>{…}</Component></…>
};
```

**Comment by thure** [comment]
I think it bears repeating, the term ‘main’ in this context is being used _the same way any component in Aurora is named_. In this case, because the component is centrally concerned with the main content area, the element in question is `<main>`.

This _does not mean_ an app should only ever have one invocation of `Main`. If anything, `Main` should be used anywhere that ordinarily would render a `<main>` element, e.g. for each `page` in a `react-router`-oriented app.

I'm struggling to come up with other HTML-linked tag names this component could be called, but I'm amenable to suggestions.

**Comment by thure** [comment]
> Requires special hooks (useMainContext) that aren't intuitively related sidebar semantics

In #3141 I've added the `useSidebar` hook which aliases to the sidebar-related values in `MainRoot`’s context as well as adds simple utilities like `openSidebar`, `closeSidebar`, and `toggleSidebar`.
