### ISSUE TITLE
[composer-app] black box e2e tests

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#3257]
Simulate basic usage of Composer by two browsers.

Roughly:
* Initialize HALO identity on both browsers.
* Create invitation on Browser A
* Accept invitation on Browser B
* Write text on Browser A, observe in Browser B
* Write text on Browser B, observe in Browser A

# Later?
Using saved browser local storage, ensure reconnection and resynchronization to peer can occur.

# Questions
* Can/should we run a KUBE? How could we isolate signalling issues?
* Can/should we run the app from localhost or a testing KUBE?
* What is the meaning of life?

**Comment by nferch** [comment]
@wittjosiah wrote this up just a few minutes before discovering a lot of it already exists.

Pretty fun to run it with --inspect and see it in action.

I think my questions still hold true though, curious how this works with signalling and whether we should figure out how to include KUBE in the test. Think it might be useful to include DNS and HTTPS in this as well since localhost can mask a lot of problems.

**Comment by wittjosiah** [comment]
@nferch So currently it's just using the default signalling config, which looks something like this:
```
    signaling:
      - server: wss://kube.dxos.org/.well-known/dx/signal
      - server: wss://dev.kube.dxos.org/.well-known/dx/signal
```
I don't love that it's using the prod signalling in CI, we've definitely encountered situations once or twice where an outage in the signal server causes CI failures. This is another issue that running a signal server in CI would probably help with because we could configure the apps to use that when running in CI.

The tests are currently run for localhost but not using the vite dev server, in CI it's running on the bundled output of the apps (which is what is published as well). I'm unsure if we'd want to go to the trouble of publishing to a KUBE and testing from there as a part of CI for a PR, but I could see how something like that would be useful, perhaps as a scheduled job? We're already publishing to dev KUBE on every merge to `main`, so that might amount to just pointing the playwright tests to run off of the dev KUBE instead?

**Comment by nferch** [comment]
@wittjosiah I think the question is around how black box we want the tests to be. For something more akin to an integration test, running just the signalling server part of KUBE (akin to how Gravity currently works) is probably fine.

If we want a black box e2e test, we'd want to deploy as much of the stack as we can in as much isolation as we can, avoiding touching as much of our live runtimes as much as possible.

I don't think there's a lot between where this road and the KUBE CI road are, going investigate more on that end and think about how we're using the containers on this side.
