### ISSUE TITLE
[composer-extension] new issue experience not enhanced on github

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3289]
Right now composer swaps only when editing an issue, not yet when creating a new one.

**Comment by thure** [comment]
This presents a tricky design problem… creating a new issue doesn’t reserve an issue slug (number) that collaborators can update with.

Collaborators would essentially work on a draft until someone finally submits it for the first time, but neither Github nor Composer knows whether a user wants to collaborate on an existing draft or start a new one when a user visits the new issue page.

I think one flow could be:

1. When a user visits Github’s new issue page, embedded Composer shows a list of documents tagged as new issue drafts (badged by member presence), or an option to create a new draft.
2. If the user creates a new draft, embedded Composer tags it as a draft so collaborators will see it in the chooser.
3. Collaborators title the issue using the document title in echo
  - I think this implies we need title syncing for other flows too
4. When a collaborator submits the new issue to Github for saving, the draft tag is replaced by the new issue tag
  - this might mean we need the user to set a PAT; if we rely on the DOM, I anticipate Github would submit the form and navigate to create the new issue, which prevents us from making a certain connection between a draft document and the created issue. 
5. When a collaborator tries to submit the issue after it has already been submitted (which we know because it no longer has the draft tag but the user is on the new issue page), embedded Composer responds the same way as with other stale issues by asserting the user needs to reload, or in this case navigate to the created issue, or set a PAT so Composer can use the API to update the issue.
