### ISSUE TITLE
[composer-extension] composer doesnt always open

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3397]
- after editing a comment, composer doesn't come up again when editing the main issue body
- after creating a new issue, and giving it a label, composer will not open when editing that issue again

**Comment by wittjosiah** [comment]
test comment

**Comment by wittjosiah** [comment]
So I reproduced this and initially I though you were right because I reproduced it by adding the above comment, however upon further debugging it doesn't happen every time I edit the comment - to this point it seems a little random (but might just not understand the trigger yet).

What seems to be happening though is that the dom nodes for the form are recreated and so the injected iframe is lost. A couple solutions come to mind:
1) Try to figure out which nodes are being updated, watch for that and re-inject the iframe
2) Add an event listener to the `Edit` button and re-inject the iframe if it's missing

2) seems a little simpler so I'll try that solution first and see how it goes.
