### ISSUE TITLE
Long-running client test

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#3607]
Have continuous, long-running test that simulate a simple user activity

e.g.
- User is a member of several spaces of varying sizes
- Makes modifications to spaces
- Client goes offline for different periods of time and needs to resynchronize

# Assertions
* Client can connect and replicate to peers
* Data can replicate in a reasonable amount of time
* When failures occur, there is sufficient feedback to the user

# Open questions
- Should this run under the existing gravity testrunner or something different?
- What manages the lifecycle of the test?
- Where does the observability data for the test go? Is it alongside our production data (with a DD tag so we can easily filter it) or somewhere else?

**Comment by richburdon** [comment]
Suggestions:
- replace "user" with "agent" (term we use for peers; not the actual agent service)
- "testrunner" means "testbench"?
- test should be from the perspective of N peers (rather than single user); e.g., test that all peers have same replica of dataset at each epoch
- able to configure epoch periods (and on/off)
- able to configure behavior of agent (e.g., how ready/chatty; how often/for how long goes offline)

**Comment by nferch** [comment]
Merged back into https://github.com/dxos/dxos/issues/3515
