### ISSUE TITLE
PeerLeft is not coming through

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#4060]
PeerLeft is not coming through during the testing - this seems to be the big/main problem, it cause peer to keep to reconnecting to other peer even if it's already succeeded with the invitation, which also results in stuck connections;

**Comment by nferch** [comment]
@egorgripasov PTAL and update as you make progress!

**Comment by egorgripasov** [comment]
Some updates on further investigation:
Atm the issue appears to be on the Signal Server side:
There are 2 possible situations when we should emit `PeerLeft`
- Peer is left by timeout - it seems to be working on the signal server side, but won't help with the original issue, because the timeout is quite big (120 seconds)
- Peer has unsubscribed from swarm, we need to emit `PeerLeft` right away; - This is not implemented atm. It probably requires some thinking re consistency with the other signal server instances, because peer might disconnected from one signal server instance just because of the err, while still connected to other signal server instance(s), so we don;t want treat that as a intentional disconnect
