### ISSUE TITLE
update the main dxos.org website

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4095]
## Motivation

The website needs to be a more welcoming, encompassing introduction to individuals finding out about DXOS. With Strange Loop incoming, we expect an increase in visitors.

## Finish Line

The website needs to answer the following questions:

> 1. What is it, in meaningful conceptual anchors/buzz words/memes? (relate it to other things they know)
> 2. Does it actually work? (show it working)
> 3. What's the code look like? (show code snippets)
> 4. How can I play with it? (Interactive code sample, embedded or codesandbox)
> 5. How does it *really* work? (brief, technical explanation of the features, link to docs for more detail)

## Scope

We'll scope this to one week (4 days) to get a draft of the website.

**Out of scope:**

- altering the brand

**Comment by richburdon** [comment]
Re https://deploy-preview-213--qa-dxos-web.netlify.app first draft:

- The site as presented makes us look like Composer is the main product -- not ECHO. I think the first section should be more like https://redis.io showing a code snippet and how simple it is to create a collaborative app. This could be embedded or video + code.

- I don't think we should call out the name Composer in a heading. I think structurally having a prominent section for examples, that showcase the different plugins is right. I think it would be better to flush out this section instead of the separate "Example Apps" section at the bottom (which should just be in the API/docs).

- visually i don't think the video "insert" looks good on the geometry field. it might be better in a full width solid color section.

**Comment by jessmartin** [comment]
@richburdon and I just spoke about website priorities and boiled it down:

**Website Revamp**
- Big Top Header can just be text for now (no video, no image). We'll bump the font size up.
- Next section: 3 side-by-side collaborative demos in (roughly) the style of the videos I've already recorded.
    1. Stacks: live documents being edited on both sides, re-ordering the docs, and multiple media types
    2. Tables: not sure what the demo is yet.
    3. Kanban: not sure what the demo is yet. 
- Existing "Platform + 6-up" section.

Done! For now, we'll cut the code example, but if we have time we'll bring back a _single_ larger code sample showing off ECHO reading and writing data.

**Plugins Quick Start Docs page** #3938 (copying the below to this issue)
- Prose description of how to quickly get started building a plugin
- Short description of Composer
- Video of composer in action
- Link to composer / labs

**Comment by jessmartin** [comment]
It's getting close to ready.

A few known things I'd like to fix:
- "Check out these nifty examples of things you can build on top of the DXOS Platform." -> rewrite this copy
- Include the CTA in the header, top right
- Add two more demo recordings
