### ISSUE TITLE
[stack] All of main area, including margins, should be droppable

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#4697]
- [x] drop ring is cut off by app chrome
- [ ] entire main area should be droppable

**Comment by thure** [comment]
> drop ring is cut off by app chrome

This is either intentional (top edge of droppable area is occluded by the topbar because the stack is scrolled) or no longer an issue.

https://github.com/dxos/dxos/assets/855039/88b497e9-53eb-418d-9321-acd6f962381f

> entire main area should be droppable

This is nontrivial and may need reprioritization. Since the other issue is mitigated, I’m marking this as P2 for now, though please update as needed.

**Comment by wittjosiah** [comment]
@thure this seems reasonable to me, but can we elaborate on "non-trivial" here for the sake of future prioritization?

**Comment by thure** [comment]
Yes, I’d estimate as 3 points:
• add a layout variant of Stack which fills the inline axis and pads sections such that they have the same maximum content size as they do now
• StackMain stretches the Stack tile to fill the block axis
