### ISSUE TITLE
API Review

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4745]
Triage major decisions for 0.4 release.
Consider future proofing requirements.

- [ ] `obj.id` vs. `obj[base]` vs. `obj.__meta` vs. `obj@foo` vs. `getSpaceForObject(obj)`
- [ ] Query/Filter.from
- [ ] links/references (strong/weak; RI)
- [ ] Expando/TypedObject/EchoObject
- [ ] Schema (zod/effect)
- [ ] Don't export SpaceProxy
- [x] https://github.com/dxos/dxos/pull/4757
- [ ] export schema with data snapshot
- [ ] deprecate protobuf
- [ ] FQ type names
- [ ] https://github.com/dxos/dxos/issues/5407
- [ ] #5326

**Comment by wittjosiah** [comment]
echo api notes I have which we should review:
- dangling references are not typesafe
	- e.g., create a folder, add an object, delete that object without removing from the folder, now mapping over that folders items one will be undefined even though the types say otherwise
- signals vs multicast observable
- signals when deleted
- query update fires on object changes
- need to make it clearer for people how to subscribe to object changes in non-react model
- symbol vs __ vs @ vs fn
- include id, __typename, __schema when spreading object?
- `batch` api?
- array mutation helpers
```
const objectIndex = grid.collection.objects.findIndex((object) => object.id === id);
if (objectIndex !== -1) {
  grid.collection.objects.splice(objectIndex, 1);
}
```
- map/record data type
- factor out `TypedObject` to be able to use elsewhere
	- maybe for providing "typename" to graph datums
	- makes it simpler for dragging graph datums into ECHO, all serializable datums will "just work" as expandos
	- potentially replace the thin `deepsignal` layer with our own proxy layer that we have more control over
- creating local-only spaces
- creating spaces without identity
- looking up spaces by name
- integrate ephemeral data feed

**Comment by wittjosiah** [comment]
We met today and reviewed most of the items listed above. We grouped the issues into two categories:
- now, things that should be worked on leading to a 0.5.0 release
- later, things that can be added incrementally or are for future consideration

These are listed below and need to be broken out into individual issues.

### Now

- [x] obj.id (only prop)
- [ ] reactive object does not depend on echo [Dima/Yaroslav]
- [ ] REVIEW: functions: e.g., `getSpaceForObject(obj)`, `metaOf(obj)` [Rich/Josiah]
  - [ ] `getSpace()`
  - [ ] `getMeta()` (keys only?)
  - [ ] `getSchema()`
  - [ ] `create(MarkdownDocument, { content: "foo" })`  
  - [ ] `ref()` (async demo)
  - [ ] `EchoObjectSchema` (remove Echo from names)
  - [ ] Expando
- [ ] use named imports instead of `* as` imports [Rich/Josiah]
- [ ] schema [Dima/Yaroslav]
  - [ ] annotations
- [ ] queries [Dima/Yaroslav]
  - [ ] Action: examples
  - [ ] deleted objects
  - [ ] graph/traversal
  - [ ] query update fires on object changes
  - [ ] need to make it clearer for people how to subscribe to object changes in non-react model
- [ ] Don't export internals (e.g., SpaceProxy); review index.ts re-exports [Rich/Josiah]

### Later

---
```ts
const Contact = S.struct({ name: S.string() })

//                         FILTER                      ORDER
db.ensureIndex({ typename: Contact.typename }, { firstName: 1, lastName: 1 }); 
// index key will be 'typename_Contact_firstName_1_lastName_1' or something

db.ensureIndex(Contact, { name: 1 }); 
```
---
```ts
// maybe
import { getMutable, isMutable } from '@dxos/client';

const result1 = db.query({ typename: 'Contact' }) // default is mutable
const result2 = db.query({ typename: 'Contact' }, { readonly: true })

const first = result2.objects[0];
console.log(isMutable(first)) // false
const mutable = await getMutable(first);
mutable.foo = 100;
```
---

- [ ] links/references (strong/weak; RI)
- [ ] backlinks?
- [ ] halo data store
- [ ] integrate ephemeral data feed
- [ ] creating local-only spaces
- [ ] creating spaces without identity
- [ ] deprecate braneframe namespace & migrate typenames (FQ type URIs)
  - `export class DocumentType extends TypedObject({ typename: 'dxos.org/type/Document', version: '0.1.0' })`
- [ ] managing async boundaries
  - [ ] remove `initialize` (improve time-to-useable-client to improve app startup sequence)
  - [ ] [sdk] space.db.{add|query|remove} should await db ready internally #5407
- [ ] signals vs multicast observable
- [ ] looking up spaces by name
- [ ] query for spaces
  - all spaces that have these properties
  - all spaces that have a least one of this schema in them
  - etc.
- [ ] [sdk] wish i could delete with a query #5326
- [ ] signals when deleted

```ts
// meteor observability api
db.query.observe({
  added(object) {},
  removed(oldObject) {},
  changed(newObject, oldObject) {}
})

// proposed api:
db.query.subscribe(({ added, removed, changed, data }) => {
  //...
  // data is all the new data
})

// btw ^ you can't optimize for "changed only" or "removed only" subscribers unless
// you break up the first argument from single function to map of functions

const query = db.query();

const diffState = createDiffState();

effect(() => {
  const objects = query.objects;
  const { added, removed } = diffState(objects);

  // or 
  const { added, removed } = diffState(query.objects);

  
})
```

- [ ] array mutation helpers

```ts
const objectIndex = grid.collection.objects.findIndex((object) => object.id === id);
if (objectIndex !== -1) {
  grid.collection.objects.splice(objectIndex, 1);
}
```
