### ISSUE TITLE
[composer] handle plugin errors more gracefully

### ISSUE THREAD

**Issue by mjamesderocher** [dxos/dxos#4977]
While working on native apps for Composer, we ran into an issue with the IPFS plugin. The error causes the whole app to not work. A plugin failure should not cause the whole app to stop working.

[Discord conversation for context](https://discord.com/channels/837138313172353095/1180035274345025617/1187031550232113215)

### Steps to reproduce

* Use the code from [this commit](https://github.com/dxos/dxos/pull/4960/commits/5c44b9ce167e723c905d79434907aac3d0fc8feb)
* Build Composer and SSC native app
* Enable the IPFS plugin then quit and reopen the app

**Comment by wittjosiah** [comment]
What happens when the app crashes? Does it hit the global error boundary or just white-screen sort of thing?

> A plugin failure should not cause the whole app to stop working

This is certainly our goal, but without going all the way to sandboxing plugins (which is on our expected path), we won't be able to fully prevent all failures from cascading.

As you work with the plugins more, if you have any ideas around specific mitigations that might be made, let us know because we're definitely open to it.

**Comment by mjamesderocher** [comment]
Right, I should have been more clear. It hangs at the loading indicator.
