### ISSUE TITLE
[stack] move "add item" at the bottom of stacks into a toolbar

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5169]

**Comment by wittjosiah** [comment]
@thure I'll tell you my interpretation and then if it aligns with @zhenyasav's intent we can update the description, I've labelled `clarify` for now since it seems we missed the description here 🙂

I think this is pushing on the toolbar designs you have for stack a bit. My interpretation was that rather than the two buttons at the bottom of the stack that the stack would have a toolbar somewhere with _stack-level_ actions vs section toolbars which house _section-level_ actions. That being said, walking through it now I'm realizing that there may be some contention for space between those two toolbars. When would should show the stack-level toolbar vs the section-level one? Presumably based on attention, but it's not obvious to me how one would simply attend the stack itself without attending a section (and even if that were possible it seems likely unintuitive).

Given all that it seems like there's maybe some more design thought required here and it's feeling more like a P2.

**Comment by zhenyasav** [comment]
the intention behind this thing is no longer valid
