### ISSUE TITLE
[composer] scrolling documents is broken

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5646]
see video, at higher zoom levels it becomes more apparent, the scroll range is artificially clipped and I can't get to all my content.

https://github.com/dxos/dxos/assets/3398896/811023f0-0a9c-4319-9b05-cce8c2c83682

**Comment by thure** [comment]
Unable to repro in any browser, zoomed-in or otherwise. We may need to pair on this to determine if the issue is limited to your device somehow (or just doesn’t repro on mine somehow).

https://github.com/dxos/dxos/assets/855039/437cb435-dc61-42ec-8822-1a1360956e27

https://github.com/dxos/dxos/assets/855039/fb94cffd-4c33-4c6c-b1d8-e5bc2ebd982f
