### ISSUE TITLE
[stack] section chrome iteration

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5733]
## Questions

- are we happy with using the whole left gutter of the section just for a centered drag handle?
- how could we support collapsing a section?
- should the section have a canonical way to expose a toolbar?
  - sections need to be able to expose a toolbar to action the content of the section
    - editor has a toolbar
    - table will likely have a toolbar
    - sketch has tools as well
  - toolbar could be rendered within the content area of the section
  - having a place for toolbars in the section however will likely make it feel more consistent
- how do the toolbar and section actions related?

**Comment by thure** [comment]
> are we happy with using the whole left gutter of the section just for a centered drag handle?
The rail (‘gutter’ refers only to negative space and ‘margin’ is overloaded) can host whatever we want! I anticipated this space would be used by other controls.

> how could we support collapsing a section?
Our best options I think are to add a button to the rail, or to add an action to the menu.

> should the section have a canonical way to expose a toolbar?
Sections that use toolbars will reserve space for their toolbars and can choose when to display them (ideally only when attended, or always if that detail proves hard to implement). Their position should be sticky to just beneath the plank heading, so toolbars should never overlap and scroll away when the bottom edge of their content scrolls away.

> how do the toolbar and section actions relate?
Without upending the design, section actions are hosted by the rail, and the toolbar is on the horizontal axis indented by the rail size. We may want a “section toolbar item” akin to “File”/“Edit”/“View” in the space at the intersection of the rail and a section’s toolbar.

I can take a stab at these ideas in Figma to get a sense for it.

**Comment by wittjosiah** [comment]
@thure I'd be curious what a stack section would look like with the chrome being across the top rather than the rail. (If we've tried this before already please refresh my memory of what the problems with it are.)

Motivating thoughts:
- we already have three-dots along the top
- toolbar across the top could host actions on the section content
- would provide something to render with section collapsed
- could render title of section object (at the very least when collapsed, perhaps always if there's space)
- UI for collapsed section would be consistent with open sections (don't need to move things around)

**Comment by thure** [comment]
There are 3 hierarchical levels of information architecture to consider:
- info & actions about the stack itself and where it sits among other planks in the deck
- actions _about_ a stack’s section and where it sits among other sections in the stack
- actions _within_ a stack’s section, relating only to the section’s content

Each layer of the IA should be able to scale significantly if we expect to facilitate actions that are frequently usable. A single nine-dots or three-dots menu will not comfortably scale to accommodate high-frequency actions or actions that require a passive signifier like expand/collapse.

If the concern is with the rail’s size, that is configurable. Rails are a common pattern even in mobile apps.

**Comment by thure** [comment]
> UI for collapsed section would be consistent with open sections (don't need to move things around)

You might not be imagining what I intend to convey about the rail, this is true for the rail and probably untrue for the 3-layer toolbar/header.

**Comment by thure** [comment]
Here is an exploration using the existing componentry available in Figma which use the rail pattern, I’ll look at a variation that does all actions horizontally next.

https://www.figma.com/file/w9HsmcQattO4slk9fLWjnh/Operating-system-v1?type=design&node-id=161%3A4049&mode=design&t=rYHIPXy69E58yPk1-1

- nine-dots is changed to type icon as we have for plank headings — whether/how we signify these are drag handles is worth exploring, though they’ll also support invoking menus like Notion
- expand/collapse action appears under that since it needs a passive signifier
- six-dots drag handle appears at the bottom-edge of stack sections for adjusting size, if available

<img width="514" alt="Screenshot 2024-02-20 at 22 46 07" src="https://github.com/dxos/dxos/assets/855039/1015547d-36c8-4531-8b0a-5596a0a87612">

**Comment by richburdon** [comment]
really like the direction. @thure can you show a stack with text, table, and sketch sections. for tables i'd like to see the x/y scroll container.

**Comment by thure** [comment]
@richburdon a somewhat hasty draft here

- StackSection overflow could potentially be visible in the rail as long as StackSection’s chrome occludes it
- The extrema for StackSection scrollbars would be x) the width from the right-edge of the rail to the right edge of the section, and y) the entire height of the section
- This isn’t meant to express an opinion about Table design specifics

<img width="1280" alt="attending stack section" src="https://github.com/dxos/dxos/assets/855039/9f0631e8-c403-4c36-afc3-4e0c2599b4a3">

**Comment by wittjosiah** [comment]
@thure one thing I'm noticing that these stack sections are missing is the menu where actions such as "go to item" or "insert above" would be housed. Where are you thinking that will go?

Separately, on the toolbar in the screenshot, I'm guessing that you envision that allow the top of whichever section has attention?

**Comment by thure** [comment]
> the menu where actions … would be housed

I’m trying out a design pattern where the type icon is both the drag handle and the menu invoker for an entitiy, throughout the app.

I do think it has discoverability issues unadorned as it is now, have been thinking of a way to make it more obvious.

> you envision that allow the top of whichever section has attention?

Yes, one reason sections need to reserve space for their toolbar is so that they can display in their static position if the section is not scrolled past the top edge of the viewport.

I think an optimization would be to show only one toolbar at a time, that of a section with attention.
