### ISSUE TITLE
[composer] fix joyride for first time users

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5990]

**Comment by jessmartin** [comment]
ideas:

- Joyride should tell people they are creating a "new account" and tell them that their data is locally stored, etc. Helps people contextualize the "log out", "invite devices", etc
- instead of just a README, have an entire Demo Space that has a stack and multiple documents, and a sketch, etc. Nice because the entire space can just be "closed" if they want to get rid of the clutter.

**Comment by zhenyasav** [comment]
this needs coordination with other dialogs like shell join panels @thure i need some help when you're back :)
