### ISSUE TITLE
[authoring] triple click should only select the current line

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#6075]
![Image](https://github.com/dxos/dxos/assets/4529818/208e2fba-c5cf-4ee9-b5fc-094987c38b5b)

Proposed solution:
- remove any padding from editor element
- all padding should be added to a parent element

**Comment by thure** [comment]
This likely has to do with how selecting the newline character works — it’s possible the browser is returning an extra bounding client rect to represent the newline, resulting in what we see here.

**Comment by wittjosiah** [comment]
There may be further context to why it is currently setup as it is in the DXOS discord, w/ search term `cm-scroller`

**Comment by marijnh** [comment]
Triple clicking, in CodeMirror, selects from the start of the clicked line to the start of the next line (if any), so that copy/cut/paste or dragging works in a line-wise way. You could define your own selection style to override this, but I think it'll mostly be annoying for users.

Padding on line elements should cause the effect in the screenshot (the default style has a vertical padding on lines). Padding on the scroller or content elements may, and is explicitly not supported.

**Comment by wittjosiah** [comment]
@marijnh thanks for confirming. That aligns with our suspicions but it's very helpful to know that for sure. I think we see a path forward here.
