### ISSUE TITLE
[stack] kbd navigation of focus to/from the rail and the section body

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6188]

**Comment by thure** [comment]
Left and right arrow keys already do this.

If focus is within either of these elements, escape should move focus to to them, at which point left and right arrow keys will do this.

It is the same number of key presses, just not chorded. Since we should arrive at a consistent way of moving focus, I think adding chorded synonyms that we cannot make consistent (since it is how text is selected in text areas) is not going to deliver significant value for the added complexity.

**Comment by zhenyasav** [comment]
what happens when there are multiple columns in a deck? doesn't L/R move between columns?

**Comment by thure** [comment]
Currently, tab is how you move between columns. I'll see if tabster's grid is up for the challenge, one obstacle may be that Deck columns can have different scroll positions.
