### ISSUE TITLE
[sdk] ability to know if identity storage has been modified from default

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6199]
This is part of "progressive multiplayer" as a piece of the "default identity" feature. The Shell needs to know whether the identity is in it's default state in order to show better shell UX when users need to join another device or otherwise visit the halo panel.

Proposal:
Composer needs a way to tell if the identity has been modified from the default "empty" state somehow. Perhaps it's an sdk feature or just a convention around a specific query that can be run in composer.

**Comment by wittjosiah** [comment]
The core problem here is: "how to show the connect to an existing identity" option at the time when someone is most likely to want to do that.

"clean identity" feels like a moving target so I think is a bad idea to chase.

#5990 is something that we're looking to add to help introduce new users to Composer.

My proposed solution to the above stated problem would be to have a set of introduction steps and the first step be presenting the option to join an existing identity instead of creating a new one:
- you should be able to skip this & skipping would just create a new identity
- if you create a new identity (without skipping) you'd continue with the rest of the introduction (i.e. joyride)
- if you join with an existing identity the joyride can be skipped since it's known that this is an existing user
