### ISSUE TITLE
[tables] investigate replacing tanstack table

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#6377]
Due to #6376, review our usage of tanstack table and scope the work it would take to replace it.

The goal of this is to have a ballpark estimate of that project such that it can be prioritized alongside other work.

This work will be unnecessary if we find a way to solve #5722 w/ tanstack table, but otherwise we need to consider alternative options for the long term.

**Comment by ZaymonFC** [comment]
# TanstackTable Usage Audit

## Summary of Issues

1. **Lack of Cell-Level Reactivity**: Entire table re-renders on data updates instead of individual cells.
2. **Over-Complexity**: Tanstack Table offers more features than required for the current use case.
3. **Deep Typesafety**: TT provides good DX for _specific_ tables on *concrete* row types. The dynamic nature of our system means that we never leverage the benefits, but we do pay the cost of the type complexity.
4. **Hidden internal data model**: Cannot directly manipulate TanstackTable's internal data model, requiring bridging code for reactive data structures.

## Functionality we currently leverage

- Sorting
- Column definition and data types
- Row pinning (top and bottom)
- Flex render (context-aware rendering)
- Row selection

### Future needs that Tanstack Table can service
- Facilities for nested data
- Column grouping
- Column re-ordering

**Comment by thure** [comment]
It seems like we wouldn’t want something like TanStack for the flattened TreeGrid we want for the next version of NavTree. This all seems like compelling motivation to build our own collaboration-first (tree)grid component for both of these use-cases.

**Comment by wittjosiah** [comment]
> It seems like we wouldn’t want something like TanStack for the flattened TreeGrid

Can you elaborate on that?
