### ISSUE TITLE
[shell] shell is not coming up on composer prod

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6538]
clicking my halo button or clicking on share a space action causes composer to freeze and doesn't bring up the shell (production)

**Comment by wittjosiah** [comment]
I noticed this a few days ago but at the time it seemed to only be happening to my profile. Good to know you're seeing it too, maybe it's related to profile size? I looked into it a bit today and why it "freezes" is because the shell iframe is unhidden but never renders anything so there's an invisible thing in front of the whole window. I've not yet been able to track down _why_ nothing is rendering though.
