### ISSUE TITLE
[stack] section drag re-ordering broken

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6562]
sometimes dragging a node from the tree into a stack drops it in an unexpected place

sometimes it freezes the ui on drop right at the moment before it can render the final positions of things, for 100s to 1000s of ms

sometimes reordering inside a stack will arrive at unexpected positions, esp if dropping an item in the first or last position

**Comment by thure** [comment]
> sometimes dragging a node from the tree into a stack drops it in an unexpected place

I tried this a number of times in a few different situations and wasn’t able to reproduce. If you can still repro this, maybe we should pair.

> sometimes it freezes the ui on drop right at the moment before it can render the final positions of things, for 100s to 1000s of ms

Drop is when ECHO “writes” the change, I think this issue likely calls for some form of thread scheduling (not something I could do alone).

> sometimes reordering inside a stack will arrive at unexpected positions, esp if dropping an item in the first or last position

Dropping an item in first or last is working for me, no repro there. Again, may need to pair to see what you’re seeing. I did notice that for expanded sections, the negative space introduced by the invisible toolbar makes positioning a little confusing, especially when edge scrolling kicks in.

We have some options for mitigating/ameliorating this, but they have significant caveats:

- map y-position of the cursor within a droppable container to the full height of its contents rather than scroll at the edges (expensive, risky ux)
- fully collapse all stack sections while dragging
  - (I’d advise this actually, since  the experience of completing the task of dragging to rearrange or copy is substantially better, and this solution is inexpensive, it just might be unexpected.)
- show the toolbar (or some other separating visual style) while dragging

**Comment by jessmartin** [comment]
> sometimes it freezes the ui on drop right at the moment before it can render the final positions of things, for 100s to 1000s of ms

dragging a sketch into Stack is horrifically slow and actually crashes the tab, both on prod and on main
