### ISSUE TITLE
navtree spec

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#7203]
## Design goals
- Reusable general purpose tree component/parts that can be restyled
- Reuse as list control in degenerative form

## Spec
- Key navigation (up/down of peers; in/out of hierarchy)
- Multi-select model (external state)
- Multi-open model (external state; e.g., support "open-to")
- Presence (activity) model
- Menu button
- ISSUE: Draggable
- ISSUE: Drop target (e.g., drop onto folder without needing special drop zone); show insert between lines
- Editable title in place
- Undo (drag/delete)

## Navtree
- Separate tree per space?

RE: https://github.com/dxos/dxos/pull/7202

https://github.com/dxos/dxos/assets/3523355/7ba0846d-a535-470a-a4f2-f6e26339ed19

**Comment by thure** [comment]
> Reusable general purpose tree component/parts that can be restyled

Yes, implemented as `TreeGrid` in #7298.

> Reuse as list control in degenerative form

Maybe `Treegrid` is reusable this way, though I’m not sure exactly what you mean.

> Key navigation (up/down of peers; in/out of hierarchy)

Absolutely, within scope of #7298.

> Multi-select model (external state)

Selection is not implemented by NavTree, so Treegrid will need to implement this as soon as a downstream component needs this feature.

By ‘external’ do you mean ‘controllable’?

> Multi-open model (external state; e.g., support "open-to")

Yes of course, though again if state is controllable, “open-to” is a matter for the downstream component to implement, or it can be provided alongside the component as a utility or hook.

By ‘external’ do you mean ‘controllable’?

> Presence (activity) model

Yes, this is on its way with NavTree, however I don’t think the icons used in this story have parity with the current design in terms of expressiveness and connectivity.

It’s unclear how these signifiers would connect with the rest of the design system for signifying attention, presence, and relatedness as the current design in Composer does. This design discards several carefully considered & coordinated signifiers which are intended to reduce cognitive load. This design does not do the due diligence of examining changes to all these connected signifiers.

I can’t recommend proceeding with this design until it resolves these issues, since proceeding with this as-is would produce design debt with no clear benefit to us or the users.

> Menu button

The NavTree already has menu buttons, however I don’t think we should change from the three dots icon to the three lines icon. The three lines icon is rarely used to open a dropdown menu as we see here, it is most often for toggling a sidebar, as such I can’t recommend proceeding with this change since it would cause unreasonable cognitive load for the user.

> Draggable, droppable

#7298 implements this.

> Editable title in place

This is not possible in the NavTree as implemented here in the story, since clicking on the title navigates to it, and right-clicking or long tapping invokes the options menu.

We could possibly bind to double-click, but this would mean either: • navigating first then editing the title if it’s already open, or • waiting some delay on click to determine if it is a single-click to navigate or a double-click to edit the title.

The title could also possibly enter edit mode and receive focus from the Rename action.

> Undo (drag/delete)

Sure, this is possible but not likely within scope of #7298.

> Separate tree per space?

This should be unnecessary.

**Comment by wittjosiah** [comment]
@richburdon @thure something else to think about re: visual design of the navtree would be https://github.com/dxos/dxos/issues/5886
